"use server";

import { getCloudflareContext } from "@opennextjs/cloudflare";
import { createGateway, generateObject } from "ai";
import {
    type GenerationConfig,
    generationConfigSchema,
    type KnowledgeBreakdown,
    knowledgeBreakdownSchema,
    type QuestionGenerationResult,
    type PipelineLog,
    clueQuestionSchema,
    fillBlankQuestionSchema,
    guessImageQuestionSchema,
    eventOrderQuestionSchema,
} from "../models/question-generator.model";
import {
    getKnowledgeBreakdownPrompt,
    getQuestionGenerationPrompt,
} from "../utils/ai-prompts";
import { generateImageWithFal } from "@/lib/fal-image-generator";

// Helper to create log entries
function createLog(
    step: string,
    status: PipelineLog["status"],
    details?: unknown,
    error?: string,
    duration?: number,
): PipelineLog {
    return {
        step,
        status,
        timestamp: Date.now(),
        duration,
        details,
        error,
    };
}

/**
 * Get the appropriate schema for a question type
 */
function getSchemaForQuestionType(type: string) {
    switch (type) {
        case "clue":
            return clueQuestionSchema;
        case "fill-blank":
            return fillBlankQuestionSchema;
        case "guess-image":
            return guessImageQuestionSchema;
        case "event-order":
            return eventOrderQuestionSchema;
        default:
            throw new Error(`Unknown question type: ${type}`);
    }
}

/**
 * Step 1: Breakdown knowledge point into structured sub-points
 */
export async function breakdownKnowledgePoint(input: string): Promise<{
    success: boolean;
    data?: KnowledgeBreakdown;
    error?: string;
}> {
    try {
        const { env } = getCloudflareContext();

        // Create AI Gateway instance
        const gateway = createGateway({
            apiKey: env.AI_GATEWAY_API_KEY || "",
        });

        console.log(
            `[Question Generator] Breaking down knowledge point: "${input}"`,
        );

        // Call AI to breakdown knowledge point
        const result = await generateObject({
            model: gateway("azure/gpt-4o"),
            schema: knowledgeBreakdownSchema,
            prompt: getKnowledgeBreakdownPrompt(input),
        });

        console.log(
            `[Question Generator] Breakdown completed - ${result.object.totalPoints} points identified`,
        );
        console.log(
            `[Question Generator] Recommended types per point:`,
            result.object.breakdown.map((p) => ({
                name: p.name,
                category: p.category,
                types: p.recommendedTypes,
            })),
        );

        return {
            success: true,
            data: result.object,
        };
    } catch (error) {
        console.error("[Question Generator] Breakdown failed:", error);
        return {
            success: false,
            error:
                error instanceof Error
                    ? error.message
                    : "Failed to breakdown knowledge point",
        };
    }
}

/**
 * Step 2: Generate a single question based on knowledge point and type
 */
async function generateSingleQuestion(
    knowledgePoint: {
        name: string;
        category: string;
        description?: string;
        difficulty?: number;
    },
    questionType: string,
): Promise<{
    success: boolean;
    data?: unknown;
    error?: string;
}> {
    try {
        const { env } = getCloudflareContext();

        const gateway = createGateway({
            apiKey: env.AI_GATEWAY_API_KEY || "",
        });

        console.log(
            `[Question Generator] Generating ${questionType} question for: "${knowledgePoint.name}"`,
        );

        // Get the appropriate schema for this question type
        const schema = getSchemaForQuestionType(questionType);

        const result = await generateObject({
            model: gateway("azure/gpt-4o"),
            schema,
            prompt: getQuestionGenerationPrompt(knowledgePoint, questionType),
        });

        const questionData = result.object;

        // Phase 2: Generate real image for guess-image questions
        if (
            questionType === "guess-image" &&
            questionData &&
            "imagePrompt" in questionData
        ) {
            console.log(
                `[Question Generator] Generating image for: "${questionData.answer}"`,
            );

            // Use the detailed imagePrompt generated by AI
            const imagePrompt =
                questionData.imagePrompt ||
                `${questionData.description}. High quality, detailed, realistic style.`;

            // Log the prompt being used for image generation
            console.log(
                `[Question Generator] Image Prompt:\n---\n${imagePrompt}\n---`,
            );

            const imageResult = await generateImageWithFal({
                prompt: imagePrompt,
                apiKey: env.FAL_API_KEY || "",
                imageSize: "landscape_16_9", // Better for quiz images
                numInferenceSteps: 50, // Increase quality (default: 28)
            });

            if (imageResult.success && imageResult.imageUrl) {
                console.log(
                    `[Question Generator] Image generated successfully: ${imageResult.imageUrl}`,
                );
                console.log(
                    `[Question Generator] Image dimensions: ${imageResult.width}x${imageResult.height}`,
                );
                // Update imageUrl in question data (type-safe for guess-image)
                questionData.imageUrl = imageResult.imageUrl;
            } else {
                console.error(
                    `[Question Generator] Image generation failed: ${imageResult.error}. Using text description only.`,
                );
            }
        }

        return {
            success: true,
            data: questionData,
        };
    } catch (error) {
        console.error(
            `[Question Generator] Failed to generate ${questionType} question:`,
            error,
        );
        return {
            success: false,
            error:
                error instanceof Error
                    ? error.message
                    : "Question generation failed",
        };
    }
}

/**
 * Main function: Generate complete question set from knowledge point
 */
export async function generateQuestionSet(config: GenerationConfig): Promise<{
    success: boolean;
    data?: QuestionGenerationResult;
    error?: string;
}> {
    const startTime = Date.now();
    const logs: PipelineLog[] = [];

    try {
        // 1. Validate config
        logs.push(
            createLog("配置验证", "running", {
                input: config.knowledgePoint,
                difficulty: config.difficulty,
                includeTypes: config.includeTypes,
            }),
        );

        const validatedConfig = generationConfigSchema.parse(config);

        logs.push(
            createLog(
                "配置验证",
                "success",
                { validatedConfig },
                undefined,
                Date.now() - startTime,
            ),
        );

        console.log(
            `[Question Generator] Starting question set generation for: "${validatedConfig.knowledgePoint}"`,
        );

        // 2. Breakdown knowledge point
        const breakdownStartTime = Date.now();
        logs.push(
            createLog("知识点拆解", "running", {
                knowledgePoint: validatedConfig.knowledgePoint,
            }),
        );

        const breakdownResult = await breakdownKnowledgePoint(
            validatedConfig.knowledgePoint,
        );

        if (!breakdownResult.success || !breakdownResult.data) {
            logs.push(
                createLog(
                    "知识点拆解",
                    "error",
                    undefined,
                    breakdownResult.error,
                ),
            );
            return {
                success: false,
                error: breakdownResult.error || "Breakdown failed",
            };
        }

        const breakdown = breakdownResult.data;

        logs.push(
            createLog(
                "知识点拆解",
                "success",
                {
                    totalPoints: breakdown.totalPoints,
                    mainCategory: breakdown.mainCategory,
                    breakdown: breakdown.breakdown.map((p) => ({
                        name: p.name,
                        category: p.category,
                        recommendedTypes: p.recommendedTypes,
                        difficulty: p.difficulty,
                    })),
                },
                undefined,
                Date.now() - breakdownStartTime,
            ),
        );

        // 3. Generate questions for each knowledge point
        logs.push(
            createLog("题目生成", "running", {
                totalPoints: breakdown.totalPoints,
            }),
        );

        const questionPromises = breakdown.breakdown.flatMap((point) => {
            // Filter question types based on config
            const typesToGenerate = validatedConfig.includeTypes
                ? point.recommendedTypes.filter((type) =>
                      validatedConfig.includeTypes?.includes(type),
                  )
                : point.recommendedTypes;

            // Generate questions for each recommended type
            return typesToGenerate.map((type) =>
                generateSingleQuestion(
                    {
                        name: point.name,
                        category: point.category,
                        description: point.description,
                        difficulty:
                            point.difficulty || validatedConfig.difficulty,
                    },
                    type,
                ),
            );
        });

        const questionGenerationStartTime = Date.now();
        const questionResults = await Promise.all(questionPromises);

        // 4. Collect successful questions
        const questions = questionResults
            .filter((result) => result.success && result.data)
            .map((result) => result.data);

        const failedCount = questionResults.filter((r) => !r.success).length;

        const questionsByType = questions.reduce<Record<string, number>>(
            (acc, q) => {
                const type = (q as { type: string }).type;
                acc[type] = (acc[type] || 0) + 1;
                return acc;
            },
            {},
        );

        logs.push(
            createLog(
                "题目生成",
                "success",
                {
                    totalGenerated: questions.length,
                    failedCount,
                    questionsByType,
                },
                undefined,
                Date.now() - questionGenerationStartTime,
            ),
        );

        const generationTime = Date.now() - startTime;

        logs.push(
            createLog("完成", "success", {
                totalTime: generationTime,
                totalQuestions: questions.length,
            }),
        );

        console.log(
            `[Question Generator] Generated ${questions.length} questions in ${generationTime}ms`,
        );

        const result: QuestionGenerationResult = {
            knowledgeBreakdown: breakdown,
            questions: questions as QuestionGenerationResult["questions"],
            totalGenerated: questions.length,
            generationTime,
            pipelineLogs: logs,
        };

        return {
            success: true,
            data: result,
        };
    } catch (error) {
        logs.push(
            createLog(
                "错误",
                "error",
                undefined,
                error instanceof Error ? error.message : "Unknown error",
            ),
        );

        console.error(
            "[Question Generator] Question set generation failed:",
            error,
        );
        return {
            success: false,
            error:
                error instanceof Error
                    ? error.message
                    : "Failed to generate question set",
        };
    }
}
